#!/usr/bin/node
// Code based on https://gist.github.com/martinsik/2031681

"use strict";

global.config=require("./conf.js");

if(config.umask)
  process.umask(config.umask);

var Core=require('./inc/core-server.js');
var core=new Core.Core();
core.init(config);

var hooks=require('./modules/base/modules/hooks/hooks.js');
var test=require('./server-test.js');
test.register({hooks: hooks});
hooks.call("server_init");

var uniq_ids={};
global.uniq_id=function() {
  var ret="";

  do {
    for(var i=0; i<4; i++)
      ret+=String.fromCharCode(Math.floor(Math.random()*26)+65);
  } while(uniq_ids[i]);

  uniq_ids[ret]=true;

  return ret;
}

global.log=function(msg, data) {
  console.log(new Date().toISOString()+": "+msg+(data?":":""));

  var str=JSON.stringify(data);
  if(str.length>80*3)
    str=str.substr(0, 80*3-3)+"...";

  console.log(str);
}
